- name: Read images.txt and pull images
  run: |
    while IFS= read -r image || [[ -n "$image" ]]; do
      echo "Pulling $image..."
      docker pull "$image"

      # Extract the image name and tag
      image_name=$(echo "$image" | awk -F/ '{print $NF}' | awk -F: '{print $1}')
      image_tag=$(echo "$image" | awk -F: '{print $2}')
      
      # If no tag is found, set it to 'latest'
      if [[ -z "$image_tag" ]]; then
        image_tag="latest"
      fi

      # Output image_tag
      echo "Extracted image tag: $image_tag"

      # Retag the image for Alibaba Cloud Container Registry
      new_image_name="crpi-itjqcsq4n73rmt0z.cn-hangzhou.personal.cr.aliyuncs.com/docker-compor/$image_name:$image_tag"
      echo "Retagging $image to $new_image_name..."
      docker tag "$image" "$new_image_name"

      # Push the image to Alibaba Cloud Container Registry
      echo "Pushing $new_image_name to Alibaba Cloud Container Registry..."
      docker push "$new_image_name"
    done < images.txt
